# Escape Sequences:
# Escape Sequences are used to print certain characters to the output stream which
# carry special meaning to the language compiler.
# Examples:
# Escape SequenceResults in
# \t    Tab Space
# \n    Newline
# \\    Backslash
# \’    Single Quote
# Multiline Strings:
# Multiline Strings are used in python through triple quotes
# '''

# a = ''' Hello
# World!
# This is a
# Multiline String.'''
# print(a)

# Strings Indexing:
# Strings in Python are indexed the same way as a list of characters, based on 0-based
# indexing. We can access elements of a string at some index by using the [] operators.

# a = "Python"
# print(a[0], a[2], a[4])
# print(a[-1], a[-3], a[-5])

#String Slicing same as list
#a = "Hello"
# Slices the string from 0 to 3 indexes
#print(a[0:3])
# Slices the string from 3 to -1(same as 4) indexes
#print(a[3:-1])

# Case Conversion Functions:
# The upper() and lower() functions are used to convert a string of letters into
# uppercase or lowercase respectively.
# The isupper() and islower() functions are used to check if a string is in all uppercase or
# lowercase respectively.

# a = "Hello"
# print(a)
# Converts string to uppercase
#print(a.upper())
# Converts string to lowercase
#print(a.lower())
# Checks if string is uppercase
#print(a.isupper())
# Checks if string is lowercase
# print(a.islower())

#Returns True if all characters in string are whitespaces
# s = ' '
# print(s.isspace())
# w = 'qwe123'
# print(w.isalnum())

#print('spandan'.isalpha())
#print('Priya'.istitle())


# join() function merges elements of a list with some delimiter string, and returns the
# result as a string.
#list = ["One",'two','three']
#join function
#s = ','.join(list)
#print(s)

# split() function splits the into tokens, based on some delimiters and returns the result
# as a list.
#split function
#print(s.split(','))

# String Formatting:
# String Formatting is done with the str.format() function.
# first = "first"
# second = "second"
# s = "Sunday is the {} day of the week, whereas Monday is the {} day of the week".format(first, second)
# print(s)

# Template Strings:
# It is recommended to be used when formatting strings generated by users. They
# make the code less complex so are easier to understand. They can be used by
# importing the Template class from the string module.
# from string import Template
# nam = 'Scaler'
# t = Template('Hey $name!')
# print(t.substitute(name = nam))
